
#' Download variable values
#'
#' @param variable variable name, a character string.
#' @param vars table of available variables, a data_frame generated by
#' list_variables() function. Defaults to NULL, in which case internal
#' table is used.
#'
#' @importFrom magrittr "%>%"
#' @export
download_table <- function(variable, vars = list_variables()) {

  # Download and process metadata
  md <- dplyr::filter(vars, Name == variable) %>%
    dplyr::mutate(resp = purrr::pmap(list(Database, Node, Name), get_tables),
                  metadata = purrr::map(resp, ~ .x$content$variables),
                  metadata = purrr::map(metadata, ~ dplyr::filter(.x, purrr::map_lgl(elimination, isTRUE))))

  metadata <- md$metadata %>%
    unlist(recursive = FALSE) %>%
    map(unlist)

  # Create json structure
  query <- list(code = metadata$code,
                selection = list(filter = "item",
                                 values = metadata$values))

  json <- list(query = list(query),
               response = list(format = "json")) %>%
    jsonlite::toJSON(pretty = TRUE, auto_unbox = TRUE)

  # Run query
  resp <- httr::POST(url = url, body = json)
  httr::content(resp, "text") %>% jsonlite::fromJSON()
}
